// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/f01a67a8f2165f4e34eab01b6c44b869b0ac3550/angular-jwt/angular-jwt.d.ts
declare namespace angular.jwt {

    interface JwtToken {
        iss?: string;
        sub?: string;
        aud?: string;
        exp?: number;
        nbf?: number;
        iat?: number;
        jti?: string;
        unique_name?: string;
    }

    interface IJwtHelper {
        decodeToken(token: string): JwtToken;
        getTokenExpirationDate(token: any): Date;
        isTokenExpired(token: any, offsetSeconds?: number): boolean;
    }

    interface IJwtInterceptor {
        tokenGetter(...params : any[]): string;
    }

    interface IAuthManagerServiceProvider {
        authenticate(): void;
        unauthenticate(): void;
        checkAuthOnRefresh(): void;
        redirectWhenUnauthenticated(): void;
    }
}
